# Generated by Django 2.2 on 2020-04-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MilkonlineApp', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
