# Generated by Django 2.2 on 2020-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MilkonlineApp', '0008_delivertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivertask',
            name='vehicle',
            field=models.CharField(default='bike', max_length=254),
            preserve_default=False,
        ),
    ]
