# Generated by Django 2.2 on 2020-04-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deliveryapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deliveryboy',
        ),
    ]
